repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files 
    args: [--maxkb=5000]
  - id: check-merge-conflict

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.2
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
    - id: ruff-format
